# Buildpack ID and metadata
[buildpack]
id = "salesforce.puppeteer"
name = "Puppeteer Cloud Native Buildpack"
version = "0.0.1"

# Stacks that the buildpack will work with
[[stacks]]
id = "heroku-18"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[metadata]
  include_files = [
    "LICENSE",
    "README.md",
    "bin/build",
    "bin/detect",
    "buildpack.toml",
  ]
